#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pyproject_metadata']

package_data = \
{'': ['*']}

install_requires = \
['packaging>=19.0']

extras_require = \
{":python_version<'3.8'": ['typing_extensions'],
 'docs': ['furo>=2023.9.10',
          'sphinx-autodoc-typehints>=1.10.0',
          'sphinx>=7.0',
          'sphinx-autodoc-typehints',
          'myst-parser'],
 'test': ['pytest-cov[toml]>=2', 'pytest>=6.2.4'],
 'test:python_version<"3.11"': ['tomli>=1.0.0', 'exceptiongroup']}

setup(name='pyproject-metadata',
      version='0.9.1',
      description='PEP 621 metadata parsing',
      author=None,
      author_email='Filipe Laíns <lains@riseup.net>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.7',
     )
