#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pyproject_metadata']

package_data = \
{'': ['*']}

install_requires = \
['packaging>=23.2']

setup(name='pyproject-metadata',
      version='0.12.1',
      description='PEP 621 metadata parsing',
      author=None,
      author_email='Filipe Laíns <lains@riseup.net>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.8',
     )
